package:
  name: "hicprediction"
  version: "0.0.3"

source:
  git_rev: 0.0.3
  git_url: https://github.com/MasterprojectRK/HiCPrediction.git

build:
  number: 0
  script: "pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - hicexplorer >=3.4.1
    - click >=7.0
    - cooler >=0.8.6
    - graphviz >=2.42.3
    - h5py >=2.10.0
    - hicmatrix >=11
    - hyperopt >=0.2.4
    - joblib >=0.14.1
    - matplotlib >=3.1.3
    - numpy >=1.18.1
    - pandas >=1.0.1
    - pybedtools >=0.8.0
    - pyBigWig >=0.3.17
    - pydot >=1.4.1
    - scikit-learn >=0.22.1
    - scipy >=1.4.1
    - tqdm >=4.43.0
  run:
    - python
    - hicexplorer >=3.4.1
    - click >=7.0
    - cooler >=0.8.6
    - graphviz >=2.42.3
    - h5py >=2.10.0
    - hicmatrix >=11
    - hyperopt >=0.2.4
    - joblib >=0.14.1
    - matplotlib >=3.1.3
    - numpy >=1.18.1
    - pandas >=1.0.1
    - pybedtools >=0.8.0
    - pyBigWig >=0.3.17
    - pydot >=1.4.1
    - scikit-learn >=0.22.1
    - scipy >=1.4.1
    - tqdm >=4.43.0